FROM oven/bun:latest AS build
WORKDIR /app
ENV PUBLIC_API_URL=/proxy-api
COPY ./package.json ./bun.lock ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun --bun run build

FROM oven/bun:latest AS production
WORKDIR /app
COPY --from=build /app/build ./build
COPY --from=build /app/package.json ./
ENV PORT=8083
ENV NODE_ENV=production
ENV TZ=America/Argentina/Buenos_Aires
ENV ORIGIN=https://portfolio.cosuarealestate.com.ar
ENV INTERNAL_API_URL=http://cosua-cre-api:3000
EXPOSE 8083
CMD ["bun", "./build/index.js"]
